[package]
name = "instrument"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.21"
regex = "1"

[lib]
name = "apoinstrument"
crate-type = ["cdylib"]
