name: Build Binary

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate App Version
      run: echo APP_VERSION=$(git describe --tags --always) >> $GITHUB_ENV

    - name: Set up CentOS 7 environment
      run: |
        sudo docker pull centos:7
        sudo docker run -v ${{ github.workspace }}:/workspace -w /workspace centos:7 /bin/bash -c "
          yum -y update &&
          yum -y install gcc make &&
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
          make release
          "
    - name: Upload to OSS
      env:
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        OSS_BUCKET: apo-oss
        OSS_ENDPOINT: https://oss-cn-hangzhou.aliyuncs.com/
      run: |
        curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
        sudo ossutil config -e $OSS_ENDPOINT -i $OSS_ACCESS_KEY_ID -k $OSS_ACCESS_KEY_SECRET -L CH -c /root/.ossutilconfig
        sudo ossutil cp install-apo-instrument.tar.gz oss://$OSS_BUCKET/apo-instrument-linux-amd64-${{ env.APP_VERSION }}.tar.gz
